### ISSUE TITLE
Question regarding the usage of the Saferpay API

### ISSUE THREAD

**Issue by thierry-rietsch** [whitesmith/saferpay-gem#8]
Hey!

I just came across your gem and figured out, that you are using the callback option of Saferpay. Is there any reason you preferred this one over the 'execute.asp' where you would get the response directly?

Kind regards,

Thierry

**Comment by pgaspar** [comment]
Hi!

Actually, there was no mention of the 'execute.asp' you're referring in the API documentation we used while building the gem. Our code is based on version 4.5 of Saferpay's Payment Page documentation.

Could you be referring to some other API?

**Comment by thierry-rietsch** [comment]
Hi!

The execute.asp is there since an earlier version of 4.5 but I guess it is not included in all documentation. I do have the documentation 'Saferpay Authorization Interface V4.6 DE.PDF' which includes the 'execute.asp' service. I found the following documentation (https://www.bs-card-service.ch/fileadmin/user_upload/com-de/Dokumente/02_CONTENT/02_E-Commerce-Versandhandel/Allpos/BS_allpos_Authorization_Interface_V43_EN.pdf) which includes also the documentation about the excute.asp.

I guess the difference is the Payment Page vs Authorization Interfaces API of Saferpay. I was just wondering as we use the "synchronous" approach to make the payment.

**Comment by pgaspar** [comment]
Yeah, I think the major difference between them is that the Authorization Interface API assumes you'll handle the payment dialogue in your website, while the Payment Page actually redirects the customer to their standard dialogues ([here's how you can get the redirection URL](https://github.com/whitesmith/saferpay-gem#generate-payment-url)).

That's why the callback makes sense, since you need to know when the customer is done filling their payment information and completing the purchase on Saferpay's dialogue.

I wasn't aware of the Authorization Interface, but the Payment Page redirection system suited us nicely, and it has the plus of not making you worry about PCI DSS compliance.

**Comment by thierry-rietsch** [comment]
Alright. Thanks for the information! I forked your project and going to add the 'synchronous' method as well to it - if that is ok for you.

**Comment by pgaspar** [comment]
Sure, thanks :smiley:
